"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const FlyBehaviour_1 = require("./FlyBehaviour");
const MallardDuck_1 = require("./MallardDuck");
const ModelDuck_1 = require("./ModelDuck");
const mallard = new MallardDuck_1.MallardDuck();
mallard.performFly();
mallard.performQuack();
const model = new ModelDuck_1.ModelDuck();
model.performFly();
model.setFlyBehaviour(new FlyBehaviour_1.FlyRocketPowered());
model.performFly();
